### ISSUE TITLE
Check Home Navbar component

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#1]
### Explanation
When the user enters the page, they can see the Azordev's company logo on the left at the top, the register and login buttons on the right, and a search engine almost in the middle.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152410720-64e470a1-d26d-480f-914b-46e27837c063.png)

### Checklist

- [x] The login button is a slightly dark blue #19456B color, with code letters #FFFFFF and the edges of the button are rounded at their tips.
- [x] The register button is in a tertiary color code #11698E , with code letters #FFFFFF and the edges of the button are rounded at the ends.
- [x] The finder is almost transparent, the magnifying glass is seen in a tertiary color with code #11698E.
- [x] The Azordev's company logo is in tertiary color with code #11698E as well as its letters.

### References

https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

**Comment by Katsu08** [comment]
How much rounded are the buttons?
