### ISSUE TITLE
Registration Page Styles

### ISSUE THREAD

**Issue by angelik0828** [Azordev/art-marketplace#47]
### Explanation:
Make style changes to this page, such as text fields, rounded corners, change button style, text styles, and color. Attached figma link to verify design and styles.
### Screenshots
![image](https://user-images.githubusercontent.com/4030477/155745525-b3ebc312-93c3-4c6c-8f1c-9f41c22d3e56.png)

![image](https://user-images.githubusercontent.com/4030477/155744011-78a19458-df92-438f-9a7f-7d732551a7e1.png)

### Checklist 
 - [ ] Change the background color of the ´#F8F1F1´ text fields.
 - [ ] Set text field border 1px color ´#11698E´.
 - [ ] Text color used in the fields and font color: ´#414141´ and regular Roboto font.
 - [ ] Change the font of the title of the text styles Roboto color in bold.
 - [ ] ´#11698E´ computer text in regular style.
 - [ ] Change the color of the button styles ´#19456B´.
 
### References
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=126%3A897

**Comment by Allislove** [comment]
Working on it.

**Comment by Allislove** [comment]
Done in PR #51
